# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Diy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Diy
  pod 'SwiftLint'
  pod 'IQKeyboardManagerSwift', '~> 6.5.0'

  target 'DiyTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SwiftLint'
  end

  target 'DiyUITests' do
    # Pods for testing
    pod 'SwiftLint'
  end

end
